# Generated by Django 2.2.5 on 2020-03-16 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0007_auto_20200316_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='rooms',
            new_name='room',
        ),
    ]
