# Generated by Django 2.2.5 on 2020-01-09 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20200107_2243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='facility',
            new_name='facilities',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='houserule',
            new_name='house_rules',
        ),
    ]
