# Generated by Django 2.2.5 on 2020-03-13 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20191218_2035'),
        ('users', '0004_auto_20191029_1523'),
    ]

    operations = [
    ]
