# Generated by Django 2.2.5 on 2020-03-13 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_auto_20200114_2248'),
        ('rooms', '0009_auto_20191029_1509'),
    ]

    operations = [
    ]
