# Generated by Django 2.2.5 on 2020-03-13 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_auto_20200114_2247'),
        ('conversations', '0002_auto_20190924_1800'),
    ]

    operations = [
    ]
