# Generated by Django 2.2.5 on 2020-03-13 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_auto_20200309_2001'),
        ('reservations', '0003_bookedday'),
    ]

    operations = [
    ]
