# Generated by Django 2.2.5 on 2020-03-13 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20191119_1723'),
        ('reviews', '0002_auto_20200114_2247'),
    ]

    operations = [
    ]
