# Generated by Django 2.2.5 on 2020-03-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_merge_20200313_2258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
        migrations.AlterField(
            model_name='review',
            name='accuracy',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='check_in',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='cleanliness',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='communication',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='location',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.IntegerField(),
        ),
    ]
